"""empty message

Revision ID: b32f9f29cdad
Revises: 
Create Date: 2017-07-31 16:28:47.462436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b32f9f29cdad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentid', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=64), nullable=True),
    sa.Column('college', sa.String(length=128), nullable=True),
    sa.Column('class_', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=64), nullable=True),
    sa.Column('task_date', sa.String(length=64), nullable=True),
    sa.Column('task_detail', sa.UnicodeText(), nullable=True),
    sa.Column('day_dis', sa.Integer(), nullable=True),
    sa.Column('task_num', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_num'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('users')
    # ### end Alembic commands ###
